{{- $root := . -}}
{{- range $_, $s := $root.Values.dockerconfig_secrets }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ print $root.Release.Name "-" $s.name | quote }}
  labels:
    release: {{ $root.Release.Name | quote }}
    app: {{ $root.Values.helm.app | quote }}
    tier: {{ $root.Values.helm.tier | quote }}
data:
  .dockerconfigjson: {{ $s.config | mustToJson | b64enc }}
{{- end }}
