{{- $root := . -}}
{{- range $_, $s := $root.Values.hook_dockerconfig_secrets }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ print $root.Release.Name "-hook-" $s.name | quote }}
  labels:
    release: {{ $root.Release.Name | quote }}
    app: {{ $root.Values.helm.app | quote }}
    tier: {{ $root.Values.helm.tier | quote }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
    "helm.sh/hook-weight": "-100"
data:
  .dockerconfigjson: {{ $s.config | mustToJson | b64enc }}
{{- end }}
