{{- $root := . }}
{{- range $_, $s := $root.Values.secrets}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ print $root.Release.Name "-" $s.name | quote }}
  labels:
    release: {{ $root.Release.Name | quote }}
    app: {{ $root.Values.helm.app | quote }}
    tier: {{ $root.Values.helm.tier | quote }}
stringData:
{{- range $_, $data := $s.data }}
  {{ $data.key }}: {{ $data.value | quote }}
{{- end }}
{{- end }}